### ISSUE TITLE
Unable to add bot to channel

### ISSUE THREAD

**Issue by Tetarchus** [4dams/music-id#64]
I get the error 'Error adding Music ID to [channel], An error occurred while adding Music ID to your channel. It might already be part of your channel. If you belive this is an error, feel free to contact me.' This was when first adding the bot to my channle and can confirm that it is not present on my channel.

Additionally, some people I mod for who use it had some issues since the latest update (the bot was present, but disappeared from the user list).

**Comment by greebowarrior** [comment]
Can confirm the issue @Tetarchus reported. (He's my mod!)
Tried adding to my alt, and got the same error.
Oddly, it was present and working in my @destabiliseuk channel this evening, but crashed in @itsgemmaedwards not long after we raided, and the error message was displaying the %ERROR% placeholder

**Comment by 4dams** [comment]
Hey 👋🏻 

Sorry for the delay, I just got onto my work machine. I have just deployed a fix for this issue preventing new channels to be added. Could you head over to https://id.adams.sh and give it another try? :)

I will also take a look at the `%ERROR%` placeholder issue. Could you please let me know if it is still occurring?

**Comment by 4dams** [comment]
I am closing this issue since the main issue has been resolved. You are still able to reply, though. :)

**Comment by Tetarchus** [comment]
Great, thank you. Can confirm that adding the bot to my channel is now working. The other issue we likely won't be able to test until later in the week, but will confirm back once we are able to test. 
Thanks
